### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by colin1715labs** [1715labs/1715-labs-website#14]
Do we have standard analytics set up (e.g. google analytics, or any other we prefer) to show us:

Number of people per day
Which parts of the website people spend time looking at
Which buttons people click on (nav bar links, zooniverse link, bio links, different contact us buttons, supported by etc)
Details on who's visited, as much as we can get (repeat vs first time views; have they ever submitted a "contact us" form?; where are they logging in from? etc)

**Comment by rogerhutchings** [comment]
related to #15

**Comment by rogerhutchings** [comment]
Not yet - how useful would that data at this stage? While we're still leaning towards consultancy, the only use I can definitely see is referrer data, and that's only if/when we start advertising

**Comment by colin1715labs** [comment]
I think it would be extremely useful / essential - but not worth delaying the launch for:

uses include:
-  After we go to an event / have a presence at a conference / do a press release etc, understand how that translates into more people looking at our site, so we can quantifiable identify which activities are actually generating interest vs each other
- Understanding which parts of the website people are looking at, so when we tailor our marketing messages, we know if people are most interested about e.g. our zooniverse heritage, our product / solution offering, or "how 1715 Labs works" etc
- giving us guidance on how we can refine and improve website, as we tweak bits going forwards (e.g. if we chance content, does that mean key metrics such as views to contact ratios, or time spent on site goes up or down etc)

for reference, I'm hoping to launch micro-budget linkedIn adverts targeted at data scientists / head of data science etc in the hours after we have a website. (realistically days)

**Comment by rogerhutchings** [comment]
I realise that, I meant that we're not doing a lot of that right now and there's not a lot of ability to do it in the future. But if it's not required for the launch, then fine

**Comment by rogerhutchings** [comment]
@colin1715labs I've added Matomo to the site. You can login at https://seventeen-fifteen-labs.matomo.cloud, login details are in 1Password.

Notes: 

- I've disabled tracking cookies to avoid having to have a cookie consent banner. See https://matomo.org/faq/general/faq_156/ for the tradeoffs, if you want to have them enabled we'll need time scheduled in for me to knock up a consent banner
- It's a 21-day trial, after which it's £19.99 / month
- We don't currently have a Privacy Policy, and we should because we're already collecting user information via the contact form.

**Comment by rogerhutchings** [comment]
Also https://ico.org.uk/for-organisations/data-protection-fee/self-assessment/
